name: TestToken

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read


jobs:
  job:
    runs-on: ubuntu-latest
    
    steps:
      
    # - name: Az CLI login
    #   uses: azure/login@v1
    #   with:
    #     client-id: ${{ secrets.CLIENT_ID }}
    #     tenant-id: ${{ secrets.TENANT_ID }}
    #     subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

    # - name: Debugging with ssh
    #   uses: lhotari/action-upterm@v1

    - name:  JWT
      run: | 
        bearerToken=${ACTIONS_ID_TOKEN_REQUEST_TOKEN}
        runtimeUrl=${ACTIONS_ID_TOKEN_REQUEST_URL}
        runtimeUrl="${runtimeUrl}&audience=api://AzureADTokenExchange"
        JWT=$(curl -H "Authorization: bearer $bearerToken" $runtimeUrl | jq -r ".value")
        echo "JWT=$JWT" >> $GITHUB_ENV

    - name: azure login with federated credentials
      run: | 
          az login --service-principal \
          -u ${{ secrets.CLIENT_ID }} \
          -t ${{ secrets.TENANT_ID }} \
          --federated-token ${JWT} 